# Generated by Django 3.2 on 2021-04-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210418_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Danh mục sản phẩm', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',), 'verbose_name': 'Người Dùng', 'verbose_name_plural': 'Người Dùng'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.FileField(default='', upload_to='uploads/user'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='categories',
            name='url_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='profile_pic',
            field=models.FileField(default='', upload_to='uploads/user'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Staff'), ('3', 'Merchant'), ('4', 'Customer')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='profile_pic',
            field=models.FileField(default='', upload_to='uploads/user'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='productvarientitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varients', to='webapp.products'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='profile_pic',
            field=models.FileField(default='', upload_to='uploads/user'),
        ),
    ]
