# Generated by Django 3.2 on 2021-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210419_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_freeship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='url_slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
