# Generated by Django 3.2 on 2021-04-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210421_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.customeruser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
