# Generated by Django 3.2 on 2021-04-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210425_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customeruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchantuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
