# Generated by Django 3.2 on 2021-04-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210425_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customuser_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='webapp.customuser'),
            preserve_default=False,
        ),
    ]
