# Generated by Django 3.2 on 2021-04-25 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_customerorder_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customuser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='product_id',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='product_id',
            field=models.ManyToManyField(to='webapp.Products'),
        ),
    ]
