# Generated by Django 3.2 on 2021-04-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210425_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=255)),
                ('discount_amt', models.CharField(max_length=255)),
                ('product_status', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='webapp.customerorder')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.products')),
            ],
        ),
    ]
