# Generated by Django 3.2 on 2021-04-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210425_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customuser_id',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerorder', to='webapp.customeruser'),
        ),
    ]
