# Generated by Django 3.2 on 2021-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210425_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='view_product',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
