# Generated by Django 3.2 on 2021-04-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_productuserviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customeruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchantuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productuserviewed',
            name='customuser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productuserview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productuserviewed',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='webapp.products'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
