# Generated by Django 3.2 on 2021-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210427_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='coupon_code',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='discount_amt',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Staff'), ('3', 'Merchant'), ('4', 'Customer')], default='4', max_length=255),
        ),
    ]
