# Generated by Django 3.2 on 2021-05-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210519_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='amount',
        ),
    ]
