# Generated by Django 3.2 on 2021-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_orderproduct_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
